### PR TITLE
Refactor tests to remove dependency 'github.com/stretchr/testify/assert'

### PR DESCRIPTION
**Pull request by jkearse3**
To make this package not have to rely on any other third party dependencies, I refactored the tests so that https://github.com/stretchr/testify is no longer necessary and allows Alice to only require the standard library. Is this okay to merge?

### CODE REVIEW

**Comment by Thomasdezeeuw** [comment]
Why did you removed the TestNew test? Because this pull request changes more then just remove the dependency.

**Comment by jkearse3** [comment]
TestNew did not affect test coverage anymore. Without it, 100 percent coverage is still achieved.

**Comment by Thomasdezeeuw** [comment]
Sure but 100% coverage doesn't mean the results of the function are checked elsewhere. And that is necessary if the test still exists.

**Comment by jkearse3** [comment]
Understood. I'll add a commit including TestNew again.

**Comment by Thomasdezeeuw** [comment]
LGTM

**Comment by justinas** [comment]
Thank you. The usage of testify/assert was really only due to my laziness when creating the library initially. Gonna merge this in.

**Pull request merged**
