### PR TITLE
removing Constructors because they unnecessarily break compatibility …

### PR DESCRIPTION
**Pull request by mvpmvh**
…with native http/net package

### CODE REVIEW

**Comment by mvpmvh** [comment]
I recognize that this breaks backwards-compatibility, but it seemed like a worthwhile break (imo).

**Comment by harlow** [comment]
Are there any updates needed to README and example code?

**Comment by justinas** [comment]
Could you elaborate on the issue? Functions (like other 'unnamed' types) [can be passed around even if the type name doesn't match](https://stackoverflow.com/questions/19334542/why-can-i-type-alias-functions-and-use-them-without-casting), as long as the underlying type is the same.

```go
package main

import (
	"net/http"

	"github.com/justinas/alice"
)

func identity(h http.Handler) http.Handler {
	return h
}

func main() {
	alice.New(identity)
}
```

**Comment by mvpmvh** [comment]
you learn something new everyday. disregard my pr.

**Pull request closed without merging**
