### PR TITLE
simplified code

### PR DESCRIPTION
**Pull request by nhooyr**
No big changes, just cleaned up some weird code.

### CODE REVIEW

**Comment by justinas** [comment]
The usage of 'weird' slice operations was a conscious decision while writing the library: we don't ever want to mess with the slices of constructors that the user passes in. Instead, we copy the list of constructors.

Similarly, for `Append()`, we don't want to modify the original Chain by appending to its `constructors` member.

Good catch on `ThenFunc()`, though. We should only merge that line, but I'm not sure how to proceed: could you revert other changes and update the PR?

**Comment by nhooyr** [comment]
Fixed. I left the change on `ThenFunc` but I changed the copy's in `Append` to use append. Just a bit cleaner.

**Comment by justinas** [comment]
```
./chain.go:83: cannot use c.constructors (type []Constructor) as type Constructor in append
./chain.go:83: append(newCons, c.constructors) evaluated but not used
./chain.go:84: cannot use constructors (type []Constructor) as type Constructor in append
./chain.go:84: append(newCons, constructors) evaluated but not used
```

Lines 1 & 3: only missing `...` to expand to variadic arguments it seems.

Lines 2 & 4: we could reassign to newCons in each to silence the messages, although slice reallocation won't happen in this case anyway.

**Comment by nhooyr** [comment]
alright fixed

**Comment by justinas** [comment]
Thanks, seems alright now, merging it in.

**Comment by nhooyr** [comment]
@justinas Wait, you said

> Similarly, for Append(), we don't want to modify the original Chain by appending to its constructors member.

Why not? It should be fine to append to the constructor member because in `New()`, we copied the user's slice. I understand why we're doing it in `New()` but shouldn't it be fine to simply append to `c.constructors` in `c.Append()`?

So turn `c.Append()` into this:

```go

func (c Chain) Append(constructors ...Constructor) Chain {
	return New(append(c.constructors, constructors...)...)
}
```

**Comment by justinas** [comment]
> Append extends a chain, adding the specified constructors as the last ones in the request flow.
> 
> Append returns a new chain, leaving the original one untouched. 

If we appended to `c.constructors`, `c` (the current chain) would change as well (except if a reallocation happened).

**Comment by nhooyr** [comment]
@justinas wouldn't a reallocation always happen though? So it should be fine.

**Comment by justinas** [comment]
As of now, the inner slice is created by `New` using `append()` and I don't think there are any guarantees on what capacity `append` sets for a new slice, so... better safe than sorry, I guess.

**Comment by nhooyr** [comment]
Ah, you are correct, append increases the capacity every reallocation by double plus one when the number of items are below 1024, and by a factor of 1.25 above.

https://github.com/golang/go/blob/master/src/runtime/slice.go#L89

**Pull request merged**
