### PR TITLE
Add AppendChain

### PR DESCRIPTION
**Pull request by agutl**

### CODE REVIEW

**Comment by justinas** [comment]
The CI broke, but that seems to be caused by a change in testify/assert. Just let me get that sorted out first.

**Comment by justinas** [comment]
Nitpick: "AppendChain" (singular) suggests only one chain is getting appended, while the argument is variadic. Is appending several chains lots of times a usual pattern? Would it be of great inconvenience to instead make it `AppendChain(Chain ch)` and simply, uh, *chain* function calls? (i.e. `alice.New(...).AppendChain(c1).AppendChain(c2)`).

Though I'm torn between that and consistency with `Append()`, which also takes a variadic argument.

On another note, could we get tests similar to ones for `Append()` which ensure that a chain is "immutable"? I understand it's only a thin wrapper over `Append()`, but... better safe than sorry!

**Comment by agutl** [comment]
About 'AppendChain(ch Chain)' vs 'AppendChain(ch ...Chain)': in my use case I call AppendChain() with only one argument so personally I don't need it to be a variadic parameter, I just made it variadic to be more consistent to Append() but meanwhile I think making it take a single argument might be better as I can't make up any use cases where simply chaining the calls would become annoying due to the amount of arguments.
Would changing the prototype to Extend(ch Chain) be fine with you?

About the testing: I can add a test with the next pull request.

**Comment by justinas** [comment]
Yeah, let's make this `Extend(ch Chain)`.

**Pull request merged**
